### ISSUE TITLE
No instructions for setting up authorization in Firebase project

### ISSUE THREAD

**Issue by limitedeternity** [AnushanLingam/moneymonitor-flutter#11]
Title

**Comment by AnushanLingam** [comment]
Issues #8 #9 and #10 all related to firebase app not being configured. 

I'll update the documentation in the next couple of days with instructions on how to configure the project from an empty firebase app to working state and then let you know.

**Comment by limitedeternity** [comment]
Thanks! Will look forward to.

**Comment by AnushanLingam** [comment]
I've updated the [README](https://github.com/AnushanLingam/moneymonitor-flutter/blob/master/README.md) with step by step instructions on how to configure firebase for use with the application.

I've managed to setup a working project using these instructions but please let me know If there are any errors or if I have missed something.

**Comment by limitedeternity** [comment]
Welp, I couldn't get Google sign-up working. But email-password sign-up does work, as well as settings.
