### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by limitedeternity** [AnushanLingam/moneymonitor-flutter#7]
> Output:  /home/limitedeternity/Desktop/moneymonitor-flutter-master/android/app/src/main/res/drawable/launch_background.xml:8: error: resource mipmap/launch_image (aka com.alingam.moneymonitor:mipmap/launch_image) not found.
  error: failed linking file resources.

**Comment by limitedeternity** [comment]
@AnushanLingam

**Comment by AnushanLingam** [comment]
Misnamed filename in `/android/app/src/main/res/drawable/launch_background.xml`

Pushed new [commit](https://github.com/AnushanLingam/moneymonitor-flutter/commit/966f50cb2dc4ac03fe02e7ef1067af9e4046b9e2) to fix issue.

If you are working with the source code I have updated the readme with more information and a link to the source for the firebase cloud functions that are needed to setup your project. 

If you just want to try the app a pre-built apk is available for android devices in the [release](https://github.com/AnushanLingam/moneymonitor-flutter/releases/tag/0.1.0) tab.

**Comment by limitedeternity** [comment]
Thanks!
